version: '3.8'

services:
  restful-export-import-api:
    image: restful-export-import-api:latest
    container_name: restful_export_import_api_springboot_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - SPRING_APPLICATION_NAME=restful-export-import-api
      - SPRING_PROFILES_ACTIVE=mysql
    networks:
      - app-network
    depends_on:
      - mysql

  postgresql:
    image: postgres:latest
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_DB: api_project_db_docker
      POSTGRES_USER: multiservice
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres:/data/postgres

  mysql:
    image: mysql:8
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: api_project_mysqldb_docker
      MYSQL_USER: multiservice
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  data:
  postgres:
  mysql: