version: '3.8'

services:
  restful-export-import-api:
    image: restful-export-import-api:latest
    container_name: restful_export_import_api_springboot_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - SPRING_APPLICATION_NAME=restful-export-import-api
      - SPRING_PROFILES_ACTIVE=postgresql
    networks:
      - app-network
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_DB: api_project_db_docker
      POSTGRES_USER: multiservice
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres:/data/postgres

networks:
  app-network:
    driver: bridge

volumes:
  data:
  postgres: